services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src:/var/www/html
    depends_on:
      - php
      - db

  php:
    container_name: php-fpm
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html

  db:
    container_name: my_sql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${db_name}
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_pass}
      MYSQL_ROOT_PASSWORD: ${db_root_pass}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
