#- name: Update apt
#  apt:
#    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

#- name: Adding docker gpg-key
#  ansible.builtin.apt_key:
#    url: https://download.docker.com/linux/debian/gpg

- name: Adding docker repo to apt
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable"
    filename: docker

- name:
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Is docker started
  service:
    name: docker
    state: started
    enabled: yes

- name: Compose install
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose

- name: chmod
  file:
    path: /usr/local/bin/docker-compose
    mode: '0755'
#- name: Install compose
#  apt:
#    name: docker-compose
#- name: Установить pip для установки Docker Compose
#  apt:
#    name: python3-pip

#- name: Установить Docker Compose
#  pip:
#    name: docker-compose

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /home/ansible/webapp

- name: Copy Dockerfile
  template:
    src: Dockerfile
    dest: /home/ansible/webapp/php

- name: Copy env
  template:
    src: .env
    dest: /home/ansible/webapp

- name: Docker Compose Up
  command: docker-compose up -d
  args:
    chdir: /home/ansible/webapp
